from .f_AccountSupervisorService import Client as FAccountSupervisorServiceClient
from .f_AccountSupervisorService import Iface as FAccountSupervisorServiceIface
from .f_AgeCheckService import Client as FAgeCheckServiceClient
from .f_AgeCheckService import Iface as FAgeCheckServiceIface
from .f_AuthService import Client as FAuthServiceClient
from .f_AuthService import Iface as FAuthServiceIface
from .f_BotService import Client as FBotServiceClient
from .f_BotService import Iface as FBotServiceIface
from .f_BuddyManagementService import Client as FBuddyManagementServiceClient
from .f_BuddyManagementService import Iface as FBuddyManagementServiceIface
from .f_BuddyService import Client as FBuddyServiceClient
from .f_BuddyService import Iface as FBuddyServiceIface
from .f_CallService import Client as FCallServiceClient
from .f_CallService import Iface as FCallServiceIface
from .f_ChannelApplicationProvidedService import Client as FChannelApplicationProvidedServiceClient
from .f_ChannelApplicationProvidedService import Iface as FChannelApplicationProvidedServiceIface
from .f_ChannelService import Client as FChannelServiceClient
from .f_ChannelService import Iface as FChannelServiceIface
from .f_LiffService import Client as FLiffServiceClient
from .f_LiffService import Iface as FLiffServiceIface
from .f_MessageService import Client as FMessageServiceClient
from .f_MessageService import Iface as FMessageServiceIface
from .f_ShopService import Client as FShopServiceClient
from .f_ShopService import Iface as FShopServiceIface
from .f_SnsAdaptorService import Client as FSnsAdaptorServiceClient
from .f_SnsAdaptorService import Iface as FSnsAdaptorServiceIface
from .f_SpotService import Client as FSpotServiceClient
from .f_SpotService import Iface as FSpotServiceIface
from .f_SquareService import Client as FSquareServiceClient
from .f_SquareService import Iface as FSquareServiceIface
from .f_TalkService import Client as FTalkServiceClient
from .f_TalkService import Iface as FTalkServiceIface
from .f_UniversalNotificationService import Client as FUniversalNotificationServiceClient
from .f_UniversalNotificationService import Iface as FUniversalNotificationServiceIface
from .ttypes import *
